### ISSUE TITLE
create statement with shapefile syntax error

### ISSUE THREAD

**Issue by sriramab** [gama-platform/gama.doc#27]
I notice when reading a shapefile attribute using the create statement the syntax in documentation is 

`create a_species from: the_shapefile with: [type:: 'TYPE_OCC', nature::'NATURE'];`

however I only get it right when I use the `read` function

`create a_species from: the_shapefile with: [type:: read('TYPE_OCC'), nature::read('NATURE')];`

version: gama 28dec2016 standalone, windows 7

**Comment by ptaillandier** [comment]
close with the latest commit

**Comment by ptaillandier** [comment]
The good one is: create a_species from: the_shapefile with: [type:: read('TYPE_OCC'), nature::read('NATURE')];
The other syntax is totally outdated ;) .
