### ISSUE TITLE
Wiki page for Operators DM and NZ are too long for Github

### ISSUE THREAD

**Issue by dphilippon** [gama-platform/gama.doc#30]
Hi, 
I don't know since when we got this problem, but the wiki is down for the operators
listed in DM and NZ. Here are some screenshots : 

<img width="1094" alt="screen shot 2017-07-26 at 3 43 28 am" src="https://user-images.githubusercontent.com/15722750/28592891-aa1f45fa-71b4-11e7-9cbe-27203c27dcb4.png">
<img width="1024" alt="screen shot 2017-07-26 at 3 43 42 am" src="https://user-images.githubusercontent.com/15722750/28592892-aa20f53a-71b4-11e7-887a-95d432333c81.png">

I don't know if we have to split them into more "classes" like A-C, D-J, K-R, S-Z or if it is happening only to me.

**Comment by AlexisDrogoul** [comment]
Works for me...
