### ISSUE TITLE
Update website contributors' year.

### ISSUE THREAD

**Issue by felixshai** [gama-platform/gama.doc#33]
Hi, everyone :
At the bottom of gama-platform website. There are contributor list with year till 2016.
Right now it's 2017 and about to be 2018.
So I think it is fine to update those information.

![image](https://user-images.githubusercontent.com/11416512/33469674-4952366a-d69f-11e7-98a3-e85fcfb69541.png)

**Comment by dphilippon** [comment]
Hi,
Thank you for the information. I've just updated the list of contributors for 2017.  I will do the same thing for 2018.
